# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-17 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('city', models.CharField(choices=[('HOU', 'Houston'), ('LA', 'Los Angeles'), ('CHI', 'Chicago'), ('RED', 'Redmond'), ('LON', 'London'), ('PHI', 'Philadelphia'), ('NY', 'New York'), ('SEA', 'Seattle'), ('AUS', 'Austin'), ('BOS', 'Boston')], default='HOU', max_length=3)),
            ],
        ),
    ]
