# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-23 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datagrid', '0003_auto_20170523_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(choices=[('Houston', 'Houston'), ('Los Angeles', 'Los Angeles'), ('Chicago', 'Chicago'), ('Redmond', 'Redmond'), ('London', 'London'), ('Philadelphia', 'Philadelphia'), ('New York', 'New York'), ('Seattle', 'Seattle'), ('Austin', 'Austin'), ('Boston', 'Boston')], default='Houston', max_length=15),
        ),
    ]
