# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-24 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datagrid', '0004_auto_20170523_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(choices=[('HOU', 'Houston'), ('LA', 'Los Angeles'), ('CHI', 'Chicago'), ('RED', 'Redmond'), ('LON', 'London'), ('PHI', 'Philadelphia'), ('NY', 'New York'), ('SEA', 'Seattle'), ('AUS', 'Austin'), ('BOS', 'Boston')], default='HOU', max_length=3),
        ),
    ]
